# Generated by Django 4.1.3 on 2025-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
