# Generated by Django 4.1.3 on 2025-04-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_image',
            field=models.FileField(blank=True, upload_to='uploads2/'),
        ),
    ]
