# Generated by Django 4.1.3 on 2025-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_image2',
            field=models.FileField(blank=True, upload_to='uploads2/'),
        ),
        migrations.AddField(
            model_name='product',
            name='uploaded_image3',
            field=models.FileField(blank=True, upload_to='uploads2/'),
        ),
    ]
